import * as React from "react";
import Head from "next/head";
import type { AppProps } from "next/app";
import { Rubik } from "next/font/google";
import { createPagesBrowserClient } from "@supabase/auth-helpers-nextjs";
import { SessionContextProvider, Session } from "@supabase/auth-helpers-react";
import { ChakraProvider } from "@chakra-ui/react";
import { Analytics } from "@vercel/analytics/react";
import { Layout } from "@/components/layout";
import { theme } from "@/lib/theme";
import "@/styles/globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export default function App({
  Component,
  pageProps,
}: AppProps<{
  initialSession: Session;
}>) {
  const [supabaseClient] = React.useState(() => createPagesBrowserClient());
  return (
    <>
      <Head>
        <title>ImageHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/SolarGalleryBold.svg" />
        <style jsx global>
          {`
            :root {
              --font-rubik: ${rubik.style.fontFamily};
            }
          `}
        </style>
      </Head>
      <SessionContextProvider
        supabaseClient={supabaseClient}
        initialSession={pageProps.initialSession}
      >
        <ChakraProvider theme={theme}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </ChakraProvider>
      </SessionContextProvider>
      <Analytics />
    </>
  );
}
